apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-collector-configmap
data:
  config.yaml: |
    extensions:
      oauth2client:
        client_id: tenant1-client-id
        client_secret: ZXhhbXBsZS1hcHAtc2VjcmV0
        endpoint_params:
          audience: tenant1-client-id
        token_url: http://hydra:4444/oauth2/token

    receivers:
      otlp:
        protocols:
          grpc:

    exporters:
      otlp:
        endpoint: sample-tempo-observatorium:8090
        tls:
          ca_file: /var/run/tls/gateway/ca/ca.crt
        auth:
          authenticator: oauth2client
        headers:
          X-Scope-OrgID: tenant1

    service:
      telemetry:
        logs:
          level: debug
      extensions: [oauth2client]
      pipelines:
        traces:
          exporters: [otlp]
          receivers: [otlp]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetry-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry-collector
  template:
    metadata:
      labels:
        app: opentelemetry-collector
    spec:
      containers:
      - name: opentelemetry-collector
        image: otel/opentelemetry-collector-contrib:0.82.0
        command: ["/otelcol-contrib", "--config=/conf/config.yaml"]
        volumeMounts:
        - mountPath: /conf
          name: opentelemetry-collector-configmap
        - mountPath: /var/run/tls/gateway/ca
          name: ca
      volumes:
      - name: opentelemetry-collector-configmap
        configMap:
          name: opentelemetry-collector-configmap
      - name: ca
        configMap:
          name: observatorium-public-ca
---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-collector
spec:
  type: ClusterIP
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
  selector:
    app: opentelemetry-collector
