{{- if .Values.observatorium.enabled }}
{{ $dict := dict "ctx" . "component" "observatorium" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tempo.resourceName" $dict }}-tenants
  namespace: {{ .Release.Namespace | quote }}
data:
  tenants.yaml: {{ toYaml .Values.observatorium.tenants | b64enc }}
{{- end }}
