---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - tempo.grafana.com
  resources:
  - tempomicroservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tempo.grafana.com
  resources:
  - tempomicroservices/finalizers
  verbs:
  - update
- apiGroups:
  - tempo.grafana.com
  resources:
  - tempomicroservices/status
  verbs:
  - get
  - patch
  - update
