# permissions for end users to view tempomicroservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tempomicroservices-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: tempo-helm-operator
    app.kubernetes.io/part-of: tempo-helm-operator
    app.kubernetes.io/managed-by: kustomize
  name: tempomicroservices-viewer-role
rules:
- apiGroups:
  - tempo.grafana.com
  resources:
  - tempomicroservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tempo.grafana.com
  resources:
  - tempomicroservices/status
  verbs:
  - get
