apiVersion: tempo.grafana.com/v1alpha1
kind: TempoMicroservices
metadata:
  name: sample
spec:
  chart: tempo-distributed
  values:
    traces:
      otlp:
        grpc:
          enabled: true
    queryFrontend:
      query:
        enabled: true
