{{- if .Values.observatorium.openshift.enabled }}
{{ $dict := dict "ctx" . "component" "observatorium" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tempo.resourceName" $dict }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.labels" (dict "ctx" .) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tempo.resourceName" $dict }}
subjects:
- kind: ServiceAccount
  name: {{ include "tempo.resourceName" $dict }}
  namespace: {{ .Release.Namespace }}
{{- end }}
