{{- if .Values.observatorium.enabled }}
{{ $dict := dict "ctx" . "component" "observatorium" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tempo.resourceName" $dict }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.labels" $dict | nindent 4 }}
  {{- with .Values.observatorium.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "tempo.selectorLabels" $dict | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tempo.podLabels" $dict | nindent 8 }}
        {{- with .Values.observatorium.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config.tenants: {{ include (print $.Template.BasePath "/observatorium/secret-observatorium.yaml") . | sha256sum }}
        checksum/config.rbac: {{ include (print $.Template.BasePath "/observatorium/configmap-observatorium.yaml") . | sha256sum }}
        {{- with .Values.observatorium.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "tempo.resourceName" $dict }}
      {{- with .Values.observatorium.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      enableServiceLinks: false
      containers:
        - name: observatorium
          image: {{ include "tempo.imageReference" $dict }}
          args:
            {{- $scheme := "http" }}
            {{- if .Values.server.tls.enabled }}
              {{- $scheme = "https" }}
            {{- end }}
            - --web.listen=0.0.0.0:8080 # proxies Tempo API and optionally Jaeger UI
            - --web.internal.listen=0.0.0.0:8081 # serves health checks
            - --traces.tenant-header=x-scope-orgid
            - --traces.tempo.endpoint={{ $scheme }}://{{ include "tempo.resourceName" (dict "ctx" . "component" "query-frontend") }}:3100 # Tempo API upstream
            - --rbac.config=/conf/rbac/rbac.yaml
            - --tenants.config=/conf/tenants/tenants.yaml
            {{- if .Values.traces.otlp.grpc.enabled }}
            - --grpc.listen=0.0.0.0:8090 # proxies Tempo Distributor gRPC
            - --traces.write.endpoint={{ include "tempo.resourceName" (dict "ctx" . "component" "distributor") }}:4317 # Tempo Distributor gRPC upstream
            {{- end }}
            {{- if .Values.queryFrontend.query.enabled }}
            - --traces.read.endpoint={{ $scheme }}://{{ include "tempo.resourceName" (dict "ctx" . "component" "query-frontend") }}:16686 # Jaeger UI upstream
            {{- end }}
            {{- if .Values.observatorium.tls.cert }}
            - --tls.server.cert-file=/var/run/tls/public/cert/tls.crt # TLS of public HTTP (8080) and gRPC (8090) server
            - --tls.server.key-file=/var/run/tls/public/cert/tls.key
            {{- end }}
            {{- if .Values.server.tls.enabled }}
            - --traces.tls.cert-file=/var/run/tls/internal/certs/tls.crt # client certificate for connection to Tempo
            - --traces.tls.key-file=/var/run/tls/internal/certs/tls.key
            - --traces.tls.ca-file=/var/run/tls/internal/certs/ca.crt
            - --tls.internal.server.cert-file=/var/run/tls/internal/certs/tls.crt
            - --tls.internal.server.key-file=/var/run/tls/internal/certs/tls.key
            {{- end }}
            - --log.level=info
          ports:
            - containerPort: 8080
              name: public
              protocol: TCP
            - containerPort: 8081
              name: internal
              protocol: TCP
            {{- if .Values.traces.otlp.grpc.enabled }}
            - containerPort: 8090
              name: grpc-public
              protocol: TCP
            {{- end }}
          {{- with .Values.observatorium.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.observatorium.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.observatorium.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /conf/rbac
              name: rbac-config
            - mountPath: /conf/tenants
              name: tenants-config
            {{- if .Values.server.tls.enabled }}
            - mountPath: /var/run/tls/internal/certs
              name: tempo-internal-certs
            {{- end }}
            {{- if .Values.observatorium.tls.cert }}
            - mountPath: /var/run/tls/public/cert
              name: observatorium-public-cert
            {{- end }}
        {{- if .Values.observatorium.openshift.enabled }}
        - name: opa-openshift
          image: quay.io/observatorium/opa-openshift:main-2023-11-15-8ed318e
          args:
            - --web.listen=:8082
            - --web.internal.listen=:8083
            - --web.healthchecks.url=http://localhost:8082
            - --opa.package=tempomicroservices
            - --opa.admin-groups=system:cluster-admins,cluster-admin,dedicated-admin
            {{- range .Values.observatorium.tenants }}
            {{- if not .oidc }}
            - --openshift.mappings={{ .name }}=tempo.grafana.com
            {{- end }}
            {{- end }}
            - --log.level=info
          ports:
            - containerPort: 8082
              name: public
              protocol: TCP
            - containerPort: 8083
              name: opa-metrics
              protocol: TCP
        {{- end }}
      {{- with .Values.observatorium.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with .Values.observatorium.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.observatorium.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: rbac-config
          configMap:
            name: {{ include "tempo.resourceName" $dict }}-rbac
        - name: tenants-config
          secret:
            secretName: {{ include "tempo.resourceName" $dict }}-tenants
        {{- if .Values.server.tls.enabled }}
        - name: tempo-internal-certs
          secret:
            secretName: {{ include "tempo.resourceName" $dict }}-certs
        {{- end }}
        {{- if .Values.observatorium.tls.cert }}
        - name: observatorium-public-cert
          secret:
            secretName: {{ .Values.observatorium.tls.cert }}
        {{- end }}
{{- end }}
