{{- if .Values.observatorium.enabled }}
{{ $dict := dict "ctx" . "component" "observatorium" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tempo.resourceName" $dict }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.labels" (dict "ctx" .) | nindent 4 }}
  annotations:
    {{- range .Values.observatorium.tenants }}
    {{- if not .oidc }}
    serviceaccounts.openshift.io/oauth-redirectreference.{{ .name }}: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ include "tempo.resourceName" $dict }}"}}'
    {{- end }}
    {{- end }}
    {{- with .Values.observatorium.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
